host = "0.0.0.0"  # optional
port = 8080
endpoint = "/"  # optional

[[repo]]
name = "username/repo-name"
exec = "touch file1"

[[repo]]
name = "username/repo-name"
exec = "sh /home/user/scripts/script.sh"

[[repo]]
name = "jieggii/puffy"
exec = "bash /home/jieggii/scripts/alert.sh"
