port = 8080             # (required)
                        # port to listen to

#host = "0.0.0.0"       # (optional, default: "0.0.0.0")
                        # host to listen to

#endpoint = "/"         # (optional, default: "/") 
                        # endpoint to listen to

#shell = "/usr/bin/sh"  # (optonal, default: "/usr/bin/sh") 
                        # shell to use when running command from $repos[i].exec
                           
#workdir = "/"          # (optional, default: "/") 
                        # workdir to go to when running command from $repos[i].execute

[[repos]]
#name = "username/repo"   # (required)
                          # name of the repository in <username>/<repo-name> format

#shell = "/usr/bin/fish"  # (optional, default: $shell) 
                          # overwrite $shell for this repository

#workdir = "/root/repo"   # (optional, default: $workdir) 
                          # overwrite $workdir for this repository

#exec = "./script.fish"   # (required)
                          # command to execute when push event is received
