host = "0.0.0.0"  # optional
port = 8080
endpoint = "/"  # optional

[[repo]]
name = "username/repo-name"
secret = "my super secret"
exec = "/usr/bin/touch /root/hewwo-cutie^^"

[[repo]]
name = "username/repo-name"
secret = "qwerty12345"
exec = "/usr/bin/sh /home/user/scripts/script.sh"
