host = "0.0.0.0"         # (optional, default: "0.0.0.0")
                         # host to listen to

port = 8080              # (required)
                         # port to listen to

endpoint = "/"           # (optional, default: "/") 
                         # endpoint to listen to

shell = "/usr/bin/bash"  # (optonal, default: "/") 
                         # shell to use when running command from $repos[i].exec
                           
workdir = "/"            # (optional, default: "/") 
                         # workdir to go to when running command from $repos[i].exec

[[repos]]  # full repository example
name = "username/repo"   # (required)
                         # name of the repository in <username>/<repo-name> format

shell = "/usr/bin/fish"  # (optional, default: $shell) 
                         # overwrite $shell for this repository

workdir = "/root/repo"   # (optional, default: $workdir) 
                         # overwrite $workdir for this repository

exec = "./script.fish"   # (required)
                         # command to execute when push event is received

[[repos]]  # the most simple repository example
name = "username/repo-name"
exec = "/home/username/scripts/alert.sh"

# other repository examples
[[repos]]  
name = "username/repo-name"
workdir = "/home/username/repo-name/"
exec = "git pull"

[[repos]]
name = "username/website"
workdir = "/home/username/repos/website/"
exec = "bash scripts/on-push.bash"
